### LOGIN ###
POST  https://devops.cloudshellcolony.com/api/accounts/devops/login HTTP/1.1
content-type: application/json

{
  "email": "ophir.h@quali.com",
  "password": "Bla1Bla2Bla3!"
}
### LONG TOKEN ###

POST https://devops.cloudshellcolony.com/api/token/longtoken HTTP/1.1
content-type: application/json
{
  "email": "ophir.h@quali.com",
  "password": "Bla1Bla2Bla3!"
}