name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
      - run: docker login -u colonysamples -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: docker-compose push
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "deploy containers!"
  