version: "3.3"
services:
  ui:
    image: colonysamples/movies-ui
    ports:
      - 80:80
  api:
    image: colonysamples/movies-api
    ports:
      - 7000:7000
    environment: 
      - COLONY_PUBLIC_ADDRESS
  db:
    image: mongo
    ports:
      - 27017:27017
    