version: "3.3"
services:
  ui:
    image: colonysamples/movies-ui
    ports:
      - 80:80
  api:
    image: colonysamples/movies-api
    ports:
      - 4000:4000
  db:
    image: mongo
    ports:
      - 27017:27017
    